blank_issues_enabled: true
contact_links:
  - name: 🗂️ Project Board
    url: https://github.com/orgs/pesu-dev/projects/4
    about: View the project board for ongoing work and updates.

  - name: 🗨️ GitHub Discussions
    url: https://github.com/orgs/pesu-dev/discussions
    about: Use GitHub Discussions for general Q&A and brainstorming.

  - name: 💬 Join the PESU Developer Group Discord Server
    url: https://discord.gg/eZ3uFs2
    about: Join our Discord for help with OAuth2 Portal integration, support, or development.
